(() => {
  if(Number(new URLSearchParams(location.search).get("module"))!==3)return;
  const key="engineerAiPatternsModuleProgress",s=JSON.parse(localStorage.getItem(key)||"{}");s.done||={};s.answers||={};s.map||=[];s.flow||=[];s.quiz||={};
  const jobs=["設計書作成","障害対応","運用作業","コードレビュー","テスト設計","問い合わせ対応","ドキュメント作成","監視アラート対応"];
  const ex=["業務の分類","設計業務でのAI活用","障害対応でのAI活用","運用手順書のレビュー","コードレビューでのAI活用","テスト設計でのAI活用","問い合わせ対応でのAI活用","監視アラート対応"];
  const sections=[["home","モジュール概要","layout-dashboard"],["theory","基礎知識","book-open"],["patterns","業務パターン一覧","blocks"],["self","実習前自己診断","clipboard-check"],["ex","実習一覧","list-checks"],["map","業務別AI活用マップ","map"],["flow","AI導入後業務フロー","workflow"],["quiz","総合テスト","circle-check"],["results","学習結果","chart-no-axes-column"],["terms","用語集","library-big"]];
  document.title="エンジニア業務におけるAI活用パターン | AI業務活用研修";document.body.innerHTML=`<div class="m1-page"><header class="m1-header"><a class="m1-brand" href="index.html"><i data-lucide="graduation-cap"></i>AI業務活用研修</a><span class="m1-header-title">MODULE 03　エンジニア業務におけるAI活用パターン</span><div class="m1-header-actions"><span><i data-lucide="cloud-check"></i> 自動保存</span><span>受講生A</span><span class="m1-avatar">A</span></div></header><div class="m1-shell"><aside class="m1-sidebar"><div class="m1-progress-label"><span>モジュール進捗</span><b id="p">0%</b></div><div class="m1-progress"><span id="bar"></span></div><nav class="m1-nav" id="nav"></nav></aside><main class="m1-main"><div class="m1-view" id="v"></div></main></div></div>`;
  const v=document.getElementById("v"),nav=document.getElementById("nav"),save=()=>{localStorage.setItem(key,JSON.stringify(s));prog()};
  function prog(){const n=Object.keys(s.done).length,p=Math.min(100,Math.round(n/(ex.length+4)*100));document.getElementById("p").textContent=p+"%";document.getElementById("bar").style.width=p+"%"}
  function menu(a){nav.innerHTML=sections.map(x=>`<button class="${a===x[0]?"active":""} ${s.done[x[0]]?"done":""}" data-x="${x[0]}"><i data-lucide="${s.done[x[0]]?"check-circle-2":x[2]}"></i>${x[1]}</button>`).join("");nav.querySelectorAll("button").forEach(b=>b.onclick=()=>render(b.dataset.x));prog();lucide.createIcons()}
  const go=x=>`<div class="m1-actions"><button class="m1-primary" data-go="${x}">次へ <i data-lucide="arrow-right"></i></button></div>`;
  function home(){v.innerHTML=`<p class="m1-kicker">MODULE 03</p><h1 class="m1-title">エンジニア業務におけるAI活用パターン</h1><p class="m1-lead">業務工程ごとに、AIが効果的な領域と人間判断が必要な領域を整理する</p><section class="m1-card"><h2>目的</h2><p>実務におけるAIの活用可能領域を整理し、どの工程でAIを使うと効果的か、どの工程では注意が必要かを判断できるようにします。</p><p>AI導入だけを目的にせず、業務品質、安全性、検証方法、責任範囲を考慮したAI活用方法を設計します。</p></section><div class="m1-grid" style="margin-top:14px"><section class="m1-card"><div class="m1-stat">8</div><p>業務パターン</p></section><section class="m1-card"><div class="m1-stat">8</div><p>実務演習</p></section><section class="m1-card"><div class="m1-stat">4</div><p>AI活用分類</p></section></div>${go("theory")}`;v.querySelector("[data-go]").onclick=()=>render("theory")}
  function theory(){v.innerHTML=`<p class="m1-kicker">THEORY</p><h1 class="m1-title">AI活用の4分類</h1><div class="m1-concepts"><section class="m1-card m1-concept"><strong>自動化</strong><p>条件とルールが明確で、誤りの影響が小さく、結果を確認できる作業。</p><p>例: 形式変換、定型文章候補、ログ一次分類。</p></section><section class="m1-card m1-concept"><strong>補助</strong><p>AIが案・候補・要約を作り、人間が確認・修正・判断する方法。</p><p><b>多くのエンジニア業務では、この利用方法が基本です。</b></p></section><section class="m1-card m1-concept"><strong>人間判断</strong><p>設計最終承認、障害原因確定、リリース可否、本番変更承認など。</p></section><section class="m1-card m1-concept"><strong>AI利用不可・高リスク</strong><p>本番DB削除の自動実行、個人情報の外部AI入力、AIだけの契約判断など。</p></section></div><section class="m1-card" style="margin-top:16px"><h2>AI活用前の判断</h2><ol class="m1-task-list"><li>業務の目的は何か</li><li>機密情報を含むか</li><li>誤りの影響は何か</li><li>人間が結果を確認できるか</li><li>検証方法と最終責任者が明確か</li><li>AIを使う方が本当に有効か</li></ol></section><div class="m1-warning">AI利用可否は作業名だけで判断できません。重要度、入力データ、影響範囲、社内ルール、確認体制で変わります。</div>${go("patterns")}`;v.querySelector("[data-go]").onclick=()=>render("patterns")}
  function patterns(){v.innerHTML=`<p class="m1-kicker">PATTERNS</p><h1 class="m1-title">業務パターン一覧</h1><div class="m1-exercises">${jobs.map((j,i)=>`<section class="m1-exercise"><small>業務 ${i+1}</small><h3>${j}</h3><p>AI活用例: 要約、候補作成、説明、観点の抜け漏れ確認</p><p>人間判断: 仕様・影響・責任・最終承認</p><p>主なリスク: 前提誤解、誤情報、会社ルール不一致</p><p>検証: 元資料・ログ・公式情報・レビュー・実行確認</p></section>`).join("")}</div>${go("self")}`;v.querySelector("[data-go]").onclick=()=>render("self")}
  function self(){const qs=["自分の業務でAIを使用したことがありますか。","AI出力をどのように確認していますか。","AIが誤った場合の影響を考えていますか。","本番環境の作業にAIを使用したことがありますか。","AI利用に関する社内ルールを知っていますか。","AIで作業時間が増えた経験がありますか。"];const a=s.answers.self||{};v.innerHTML=`<p class="m1-kicker">SELF CHECK</p><h1 class="m1-title">実習前自己診断</h1><section class="m1-card">${qs.map((q,i)=>`<div class="m1-field"><label>${q}</label><select data-q="${i}"><option>ない</option><option>少しある</option><option>よくある</option><option>分からない</option></select></div>`).join("")}<div class="m1-field"><label>現在の業務でAIを活用したい作業</label><textarea id="selftext">${a.text||""}</textarea></div><div class="m1-actions"><button class="m1-primary" id="selfsave">自己診断を保存する</button></div></section>`;v.querySelectorAll("select").forEach((x,i)=>x.value=a[i]||"ない");document.getElementById("selfsave").onclick=()=>{const o={text:document.getElementById("selftext").value};v.querySelectorAll("select").forEach((x,i)=>o[i]=x.value);s.answers.self=o;s.done.self=true;save();alert("実習後に、AI活用方法とリスク認識がどのように変化したか確認します。")}}
  function exerciseList(){v.innerHTML=`<p class="m1-kicker">PRACTICE</p><h1 class="m1-title">実習一覧</h1><div class="m1-exercises">${ex.map((x,i)=>`<article class="m1-exercise"><div class="l2-card-head"><small>実習 ${String(i+1).padStart(2,"0")}</small><span class="l2-badge ${s.done[`ex${i}`]?"done":""}">${s.done[`ex${i}`]?"完了":"未着手"}</span></div><h3>${x}</h3><p>AIが補助できる範囲、リスク、人間が判断すべき点、検証方法を整理します。</p><button class="m1-secondary" data-i="${i}">実習を開く</button></article>`).join("")}</div>`;v.querySelectorAll("[data-i]").forEach(b=>b.onclick=()=>exercise(+b.dataset.i))}
  function exercise(i){const a=s.answers[`ex${i}`]||{};v.innerHTML=`<p class="m1-kicker">PRACTICE ${i+1}</p><h1 class="m1-title">${ex[i]}</h1><section class="m1-card"><h2>課題</h2><p>この業務について、AIで補助できる作業、人間判断が必要な作業、主なリスク、検証方法を整理してください。</p><div class="m1-field"><label>AIで補助できる作業</label><textarea id="a">${a.a||""}</textarea></div><div class="m1-field"><label>人間判断が必要な作業</label><textarea id="h">${a.h||""}</textarea></div><div class="m1-field"><label>リスクと検証方法</label><textarea id="r">${a.r||""}</textarea></div><div class="m1-actions"><button class="m1-secondary" id="back">実習一覧へ戻る</button><button class="m1-primary" id="finish">実習を完了する</button></div></section>`;const saveDraft=()=>{s.answers[`ex${i}`]={a:document.getElementById("a").value,h:document.getElementById("h").value,r:document.getElementById("r").value};save();};["a","h","r"].forEach(id=>document.getElementById(id).oninput=saveDraft);document.getElementById("back").onclick=exerciseList;document.getElementById("finish").onclick=()=>{const o={a:document.getElementById("a").value,h:document.getElementById("h").value,r:document.getElementById("r").value};if(!o.a||!o.h||!o.r){alert("すべての項目を記入してください。");return}s.answers[`ex${i}`]=o;s.done[`ex${i}`]=true;save();alert("実習を完了しました。")}}
  function map(){v.innerHTML=`<p class="m1-kicker">AI MAP</p><h1 class="m1-title">業務別AI活用マップ</h1><p class="m1-lead">自分の業務を追加し、AIの適用区分を整理します。</p><section class="m1-card"><div id="maprows"></div><button class="m1-secondary" id="addmap">業務を追加</button><div class="m1-actions"><button class="m1-primary" id="savemap">マップを保存</button><button class="m1-secondary" id="export">JSON出力</button></div></section>`;const rows=document.getElementById("maprows");const draw=()=>rows.innerHTML=s.map.map((x,i)=>`<div class="m3-map-row"><input value="${x.name||""}" data-n="${i}" placeholder="業務名"><select data-t="${i}"><option ${x.type==="AIで自動化可能"?"selected":""}>AIで自動化可能</option><option ${x.type==="AIで補助可能"?"selected":""}>AIで補助可能</option><option ${x.type==="人間判断が必要"?"selected":""}>人間判断が必要</option><option ${x.type==="AI利用を避ける"?"selected":""}>AI利用を避ける</option></select><button class="m3-remove" data-r="${i}">×</button></div>`).join("");draw();document.getElementById("addmap").onclick=()=>{s.map.push({name:"",type:"AIで補助可能"});draw()};rows.onclick=e=>{if(e.target.dataset.r!==undefined){s.map.splice(+e.target.dataset.r,1);draw()}};document.getElementById("savemap").onclick=()=>{rows.querySelectorAll("input").forEach(x=>s.map[+x.dataset.n].name=x.value);rows.querySelectorAll("select").forEach(x=>s.map[+x.dataset.t].type=x.value);s.done.map=true;save();alert("AI活用マップを保存しました。")};document.getElementById("export").onclick=()=>{const blob=new Blob([JSON.stringify(s.map,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="ai-application-map.json";a.click();URL.revokeObjectURL(a.href)}}
  function flow(){const steps=["要件資料を準備","機密情報を除外","AIに整理を依頼","AI出力を元資料と比較","不足要件を確認","関係者レビュー","人間が最終決定","設計書を承認"];v.innerHTML=`<p class="m1-kicker">WORKFLOW</p><h1 class="m1-title">AI導入後業務フロー</h1><section class="m1-card"><p>安全な設計業務フローの例です。AI出力の比較・レビュー・人間の最終決定を必ず含めます。</p><div class="m3-flow">${steps.map((x,i)=>`<div class="m3-flow-item"><b>${i+1}</b>${x}</div>`).join("")}</div><div class="m1-actions"><button class="m1-primary" id="flowok">このフローを確認した</button></div></section>`;document.getElementById("flowok").onclick=()=>{s.done.flow=true;save();alert("業務フローを保存しました。")}}
  function quiz(){const q=[["多くのエンジニア業務で基本となるAI活用は？",["補助","最終自動化","責任移譲"],0],["本番DB削除SQLの実行は？",["AI利用を避ける","自動化可能","AIだけで判断"],0],["AI出力で必要なことは？",["検証方法を設計","そのまま採用","責任をAIへ"],0],["障害対応で人間が判断することは？",["原因確定","ログ要約","時系列整理"],0],["設計書でAIが補助できることは？",["構成案の下書き","最終承認","顧客合意"],0]];const n=s.quiz.n||0;if(s.quiz.score!==undefined){const pass=s.quiz.score>=4;v.innerHTML=`<h1 class="m1-title">総合テスト結果</h1><section class="m1-result ${pass?"":"fail"}"><h2>${s.quiz.score} / 5</h2><p>${pass?"合格です。":"再学習推奨です。"}</p>${!pass?`<button class="m1-primary" id="retry">再受験する</button>`:""}</section>`;if(!pass)document.getElementById("retry").onclick=()=>{s.quiz={};save();quiz();};return}v.innerHTML=`<p class="m1-kicker">QUIZ ${n+1}/5</p><h1 class="m1-title">総合テスト</h1><section class="m1-quiz-card"><h3>${q[n][0]}</h3>${q[n][1].map((x,i)=>`<label class="m1-option"><input type="radio" name="q" value="${i}">${x}</label>`).join("")}<div class="m1-actions"><button class="m1-primary" id="next">次へ</button></div></section>`;document.getElementById("next").onclick=()=>{const c=v.querySelector('input:checked');if(!c){alert("回答を選択してください。");return;}s.quiz.a||=[];s.quiz.a[n]=+c.value;if(n<4)s.quiz.n=n+1;else{s.quiz.score=s.quiz.a.reduce((z,x,i)=>z+(x===q[i][2]?1:0),0);if(s.quiz.score>=4)s.done.quiz=true}save();quiz()}}
  function results(){v.innerHTML=`<p class="m1-kicker">RESULTS</p><h1 class="m1-title">学習結果</h1><div class="m1-grid"><section class="m1-card"><div class="m1-stat">${Object.keys(s.done).filter(x=>x.startsWith("ex")).length}/8</div><p>完了実習</p></section><section class="m1-card"><div class="m1-stat">${s.quiz.score??"-"}/5</div><p>テスト結果</p></section><section class="m1-card"><div class="m1-stat">${s.map.length}</div><p>マップ登録業務</p></section></div><div class="m1-actions"><button class="m1-secondary" id="reset">このモジュールをリセット</button></div>`;document.getElementById("reset").onclick=()=>{if(confirm("このモジュールの回答、進捗、テスト結果、AI活用マップ、業務フローをすべて削除します。よろしいですか。")){localStorage.removeItem(key);location.reload()}}}
  function terms(){v.innerHTML=`<p class="m1-kicker">GLOSSARY</p><h1 class="m1-title">用語集</h1><section class="m1-card"><dl class="l2-glossary"><dt>自動化</dt><dd>条件とルールが明確な作業を仕組みで実行すること。</dd><dt>補助</dt><dd>AIが案を作り、人間が確認・修正・判断する利用方法。</dd><dt>人間判断</dt><dd>責任、影響、合意を含む最終判断を人間が行う工程。</dd><dt>検証</dt><dd>元資料、公式情報、実環境、レビューでAI出力を確認すること。</dd></dl></section>`}
  function render(x){menu(x);({home,theory,patterns,self,ex:exerciseList,map,flow,quiz,results,terms}[x])();lucide.createIcons()}render("home");
})();
