(() => {
  if (Number(new URLSearchParams(location.search).get("module")) !== 1) return;
  const key = "ai-course-module-one-complete";
  const state = JSON.parse(localStorage.getItem(key) || "{}");
  state.completed ||= {}; state.answers ||= {}; state.quiz ||= {};
  document.head.insertAdjacentHTML("beforeend", "<style>.m1-exercise-head{display:flex;align-items:center;width:100%;gap:8px}.m1-status{display:inline-flex;align-items:center;gap:5px;margin-left:auto;padding:4px 8px;border-radius:999px;background:#f0f3f7;color:#60708a;font-size:12px;font-weight:700}.m1-status.done{background:#e7f7ee;color:#128453}.m1-status svg{width:14px;height:14px}</style>");
  const exercises = [
    ["分類", "AI・機械学習・生成AIの分類", "過去の監視データから障害発生を予測する\n顧客への返信メールを作成する\n監視アラートを重要度別に分類する\nサーバー設定手順書の下書きを作成する\n障害ログを要約する", ["業務を3つの技術に分類する", "選択理由を書く", "AIだけでは対応できない部分を示す"]],
    ["判定", "AIに任せられる業務の判定", "A: AIに任せてもよい\nB: 下書きは可能だが人間確認が必要\nC: AIに任せてはいけない\n\n障害ログ要約 / 最終原因判断 / 本番反映 / 顧客返信作成 / DB削除SQL実行 / 個人情報入力", ["各業務をA/B/Cに分類する", "判断理由を書く", "人間確認が必要な箇所を示す"]],
    ["ログ", "障害ログの原因分析", "10:02:11 ERROR Database connection timeout\n10:02:12 WARN Connection pool usage: 100%\n10:02:13 ERROR Failed to execute user search\n10:02:15 INFO Database server CPU usage: 92%\n10:02:20 ERROR Database connection timeout", ["AIにログを要約させる", "原因候補を3つ出す", "事実と推測を分ける", "人間の確認作業を書く"]],
    ["返信", "顧客問い合わせ返信文", "システムにログインできません。今日の朝までは利用できていました。早く直してください。\n\n確認事項: エラーメッセージ / 利用端末 / 発生時刻 / 他ユーザーへの影響 / パスワード変更 / ネットワーク", ["最初の返信文を作る", "不足情報を確認する", "送信可能な文章に修正する"]],
    ["手順", "サーバー設定手順書レビュー", "依頼: Ubuntu ServerにNginxをインストールし、Webサーバーを起動する手順書を作成してください。\n\n確認: OS/バージョン / 実行権限 / バックアップ / FW / 動作確認 / 切り戻し", ["AI作成手順書をレビューする", "問題点一覧を作る", "修正版と人間確認箇所を示す"]],
    ["SQL", "危険なSQLの判定", "DELETE FROM customers;\n\nDELETE FROM customers WHERE status = 'inactive';\n\n確認: WHERE条件 / 対象件数 / バックアップ / トランザクション / 承認 / ロールバック", ["危険性を説明する", "安全な確認方法を考える", "AIだけに任せられない理由を書く"]],
    ["監視", "監視アラートの分類", "A CPU使用率が5分間90%以上\nB ディスク使用率70%\nC Webサイトへの接続不可\nD バックアップ処理が1回失敗\nE データベース接続不可\nF SSL証明書の有効期限が30日後\nG 不正ログインの可能性を検知", ["緊急・高・中・低に分類する", "AIと自分の結果を比較する", "業務条件で変わる例を書く"]],
    ["設計", "設計レビューでのAI利用", "インターネット → Webサーバー1台 → データベース1台\n\n条件: 24時間利用 / 1,000人 / 個人情報保存 / 障害時も継続\n\n観点: 単一障害点 / 冗長化 / バックアップ / アクセス制御 / 暗号化 / 監視", ["AIに問題点を指摘させる", "採用できる提案を選ぶ", "最終判断が必要な項目を書く"]],
    ["情報", "個人情報を含むデータの取り扱い", "氏名: 山田太郎\n住所: 東京都〇〇区〇〇\n電話: 090-XXXX-XXXX\nメール: taro@example.com\n契約番号: C-123456\n問い合わせ: ログインできない", ["個人情報を特定する", "匿名化データを作る", "AIを使わないケースを説明する"]],
    ["テスト", "テストケース作成", "対象: ログイン画面\n仕様: 正しい場合ホームへ / 5回失敗でロック / パスワード8文字以上\n\n観点: 正常 / 異常 / 境界値 / 未入力 / 7文字 / 8文字 / 不正形式 / SQL Injection", ["AIにテストケースを作らせる", "正常系・異常系・境界値に分類する", "見落としと優先度を追加する"]]
  ];
  const quiz = [["生成AIが得意な作業は？",["文章の下書き","本番DB削除","最終承認"],0],["AIの回答はどう扱う？",["そのまま使う","根拠を人間が確認する","責任もAIに任せる"],1],["外部AIへ個人情報を入力する前に？",["匿名化と規程確認","文字を減らすだけ","何もしない"],0],["本番SQLの実行判断は？",["AI","人間の責任者","自動テスト"],1],["AIが示す障害原因は？",["確定原因","確認が必要な候補","監視ルール"],1],["返信文で確認することは？",["事実関係","文章量だけ","不要"],0],["アラート重要度に影響するものは？",["SLA・影響範囲","画面の色","モデル名"],0],["手順書に必要なものは？",["切り戻し手順","AIの感想","無制限権限"],0],["AI利用可否で確認することは？",["誤りを発見できるか","速度だけ","色だけ"],0],["最終判断の責任者は？",["人間","生成AI","ブラウザ"],0]];
  const sections=[["home","モジュール概要","layout-dashboard"],["learn","基礎を学ぶ","book-open"],["exercises","実習に取り組む","clipboard-list"],["quiz","理解度チェック","circle-check"],["checklist","AI利用チェック","shield-check"]];
  document.title="AI・機械学習・生成AIの役割 | AI業務活用研修";
  document.body.innerHTML=`<div class="m1-page"><header class="m1-header"><a class="m1-brand" href="index.html"><i data-lucide="graduation-cap"></i>AI業務活用研修</a><span class="m1-header-title">MODULE 01　AI・機械学習・生成AIの役割</span><div class="m1-header-actions"><span><i data-lucide="cloud-check"></i> 自動保存</span><span>受講生A</span><span class="m1-avatar">A</span></div></header><div class="m1-shell"><aside class="m1-sidebar"><div class="m1-progress-label"><span>モジュール進捗</span><b id="progress-value">0%</b></div><div class="m1-progress"><span id="progress-bar"></span></div><nav class="m1-nav" id="nav"></nav></aside><main class="m1-main"><div class="m1-view" id="view"></div></main></div></div>`;
  const view=document.getElementById("view"),nav=document.getElementById("nav");
  const save=()=>{localStorage.setItem(key,JSON.stringify(state));progress()};
  function progress(){const p=Math.round(Object.keys(state.completed).length/(exercises.length+2)*100);document.getElementById("progress-value").textContent=`${p}%`;document.getElementById("progress-bar").style.width=`${p}%`}
  function renderNav(active){nav.innerHTML=sections.map(x=>`<button class="${x[0]===active?"active":""}" data-view="${x[0]}"><i data-lucide="${state.completed[x[0]]?"check-circle-2":x[2]}"></i>${x[1]}</button>`).join("");nav.querySelectorAll("button").forEach(b=>b.onclick=()=>render(b.dataset.view));progress();lucide.createIcons()}
  function home(){view.innerHTML=`<p class="m1-kicker">MODULE 01</p><h1 class="m1-title">AI・機械学習・生成AIの役割と安全な業務活用</h1><p class="m1-lead">生成AIを便利な道具として使いながら、最終判断・情報管理・本番作業の責任を人間が持つための実践モジュールです。</p><div class="m1-grid"><section class="m1-card"><p class="m1-kicker">PRACTICE</p><div class="m1-stat">10</div><p>実務を想定した演習</p></section><section class="m1-card"><p class="m1-kicker">QUIZ</p><div class="m1-stat">10</div><p>理解度チェック問題</p></section><section class="m1-card"><p class="m1-kicker">GOAL</p><div class="m1-stat">80%</div><p>修了の目安</p></section></div><section class="m1-card" style="margin-top:16px"><h2>学習目標</h2><ul><li>AI・機械学習・生成AIの違いを説明できる</li><li>AIに任せる範囲と人間が確認する範囲を判断できる</li><li>ログ、メール、SQL、設計を安全にレビューできる</li><li>個人情報・機密情報を含む入力を避けられる</li></ul><div class="m1-actions"><button class="m1-primary" data-go="learn">基礎を学ぶ <i data-lucide="arrow-right"></i></button></div></section>`;view.querySelector("[data-go]").onclick=()=>render("learn")}
  function learn(){view.innerHTML=`<p class="m1-kicker">LEARNING</p><h1 class="m1-title">3つの技術を区別する</h1><p class="m1-lead">言葉が似ていても、得意なことと利用時の責任は異なります。</p><div class="m1-concepts"><section class="m1-card m1-concept"><strong>AI</strong><p>人間の判断や作業を支援・自動化する広い概念です。</p><ul><li>画像認識</li><li>音声認識</li><li>迷惑メール判定</li></ul></section><section class="m1-card m1-concept"><strong>機械学習</strong><p>過去データからパターンを学び、予測や分類を行います。</p><ul><li>障害発生予測</li><li>不正アクセス検知</li><li>需要予測</li></ul></section><section class="m1-card m1-concept"><strong>生成AI</strong><p>文章、要約、コードなど新しい内容を生成します。</p><ul><li>メール下書き</li><li>手順書作成</li><li>ログ要約</li></ul></section></div><h2 style="margin-top:26px">役割の違い</h2><table class="m1-table"><thead><tr><th>観点</th><th>AI</th><th>機械学習</th><th>生成AI</th></tr></thead><tbody><tr><td>目的</td><td>支援・自動化</td><td>予測・分類</td><td>文章・コード等の生成</td></tr><tr><td>利用例</td><td>画像・音声認識</td><td>障害予測・検知</td><td>メール・要約・下書き</td></tr><tr><td>注意点</td><td>人間が責任を持つ</td><td>データ品質を確認する</td><td>誤情報・情報漏えいを検証する</td></tr></tbody></table><div class="m1-warning"><i data-lucide="triangle-alert"></i> 生成AIは便利でも、正しいとは限りません。個人情報・機密情報の入力、本番環境への直接操作、最終判断の丸投げは行いません。</div><div class="m1-actions"><button class="m1-primary" data-go="exercises">実習に進む <i data-lucide="arrow-right"></i></button></div>`;view.querySelector("[data-go]").onclick=()=>render("exercises")}
  function exerciseList(){view.innerHTML=`<p class="m1-kicker">PRACTICE</p><h1 class="m1-title">実務演習</h1><p class="m1-lead">AIに質問し、回答を鵜呑みにせず、自分の根拠と確認項目を残してください。</p><div class="m1-exercises">${exercises.map((e,i)=>{const done=!!state.completed[`exercise-${i}`];return `<article class="m1-exercise"><div class="m1-exercise-head"><small>実習 ${String(i+1).padStart(2,"0")}</small><span class="m1-status ${done?"done":""}"><i data-lucide="${done?"check-circle-2":"circle"}"></i>${done?"完了":"未完了"}</span></div><h3>${e[1]}</h3><p>${e[3][0]}</p><button class="m1-secondary" data-ex="${i}">${done?"見直す":"実習を開く"}<i data-lucide="arrow-right"></i></button></article>`}).join("")}</div>`;view.querySelectorAll("[data-ex]").forEach(b=>b.onclick=()=>exercise(Number(b.dataset.ex)))}
  function exercise(i){const e=exercises[i],a=state.answers[i]||{};view.innerHTML=`<p class="m1-kicker">PRACTICE ${String(i+1).padStart(2,"0")}</p><h1 class="m1-title">${e[1]}</h1><section class="m1-card"><h2>演習資料</h2><pre class="m1-evidence">${e[2]}</pre></section><section class="m1-card" style="margin-top:14px"><h2>受講者への課題</h2><ol class="m1-task-list">${e[3].map(x=>`<li>${x}</li>`).join("")}</ol><div class="m1-field"><label>AIへの質問（プロンプト）</label><textarea id="prompt">${a.prompt||""}</textarea></div><div class="m1-field"><label>AIの回答で使える点・正しいと思う点</label><textarea id="correct">${a.correct||""}</textarea></div><div class="m1-field"><label>不確かな点・人間が確認すべき点</label><textarea id="verify">${a.verify||""}</textarea></div><div class="m1-field"><label>自分の最終判断と根拠</label><textarea id="judgment">${a.judgment||""}</textarea></div>${e[3].map((x,n)=>`<label class="m1-check"><input type="checkbox" data-check="${n}" ${(a.checks||[])[n]?"checked":""}><span>${x}</span></label>`).join("")}<div class="m1-actions"><button class="m1-secondary" id="back">一覧へ戻る</button><button class="m1-primary" id="complete">この実習を完了する <i data-lucide="check"></i></button></div></section>`;const collect=()=>({prompt:document.getElementById("prompt").value,correct:document.getElementById("correct").value,verify:document.getElementById("verify").value,judgment:document.getElementById("judgment").value,checks:[...view.querySelectorAll("[data-check]")].map(x=>x.checked)});view.querySelectorAll("textarea,input").forEach(x=>x.oninput=()=>{state.answers[i]=collect();save()});document.getElementById("back").onclick=exerciseList;document.getElementById("complete").onclick=()=>{const v=collect();state.answers[i]=v;if(!v.correct||!v.verify||!v.judgment||!v.checks.every(Boolean)){alert("すべての記入欄とチェック項目を完了してください。");return}state.completed[`exercise-${i}`]=true;save();alert("実習を完了しました。")}}
  function quizView(){const q=state.quiz.index||0;if(state.quiz.result!==undefined){const ok=state.quiz.result>=8;view.innerHTML=`<p class="m1-kicker">FINAL QUIZ</p><h1 class="m1-title">理解度チェック結果</h1><section class="m1-result ${ok?"":"fail"}"><h2>${state.quiz.result} / 10 問正解</h2><p>${ok?"合格です。AI利用時も、最終的に人間が検証・判断することを忘れないでください。":"80%（8問）以上で合格です。教材と実習を見直して再挑戦してください。"}</p></section><div class="m1-actions"><button class="m1-secondary" id="retry">もう一度挑戦</button></div>`;document.getElementById("retry").onclick=()=>{state.quiz={};save();quizView()};return}const item=quiz[q];view.innerHTML=`<p class="m1-kicker">FINAL QUIZ ${q+1} / 10</p><h1 class="m1-title">理解度チェック</h1><section class="m1-quiz-card"><h3>${item[0]}</h3>${item[1].map((x,i)=>`<label class="m1-option"><input type="radio" name="q" value="${i}">${x}</label>`).join("")}<div class="m1-actions"><button class="m1-primary" id="next">${q===9?"結果を見る":"次の問題へ"}</button></div></section>`;document.getElementById("next").onclick=()=>{const choice=view.querySelector('input[name="q"]:checked');if(!choice){alert("回答を選択してください。");return;}state.quiz.answers ||= [];state.quiz.answers[q]=Number(choice.value);if(q<9)state.quiz.index=q+1;else{state.quiz.result=state.quiz.answers.reduce((n,x,i)=>n+(x===quiz[i][2]?1:0),0);if(state.quiz.result>=8)state.completed.quiz=true}save();quizView()}}
  function checklist(){const list=["個人情報や機密情報を含んでいない","AIの誤りを人間が発見できる","出力結果を人間が確認できる","本番環境に直接影響しない","法律・契約・社内規程に違反しない","最終判断の責任者が決まっている","AIを使う必要性がある","入力データを匿名化できる","誤りの影響範囲を把握している","作業記録を残す必要性を確認した"];view.innerHTML=`<p class="m1-kicker">FINAL CHECKLIST</p><h1 class="m1-title">AI利用可否チェックシート</h1><p class="m1-lead">実際の業務でAIを使う前に確認してください。</p><section class="m1-card">${list.map((x,i)=>`<label class="m1-check"><input type="checkbox" data-final="${i}" ${(state.checklist||[])[i]?"checked":""}><span>${x}</span></label>`).join("")}<div class="m1-actions"><button class="m1-primary" id="save-check">チェックシートを保存</button></div></section>`;document.getElementById("save-check").onclick=()=>{state.checklist=[...view.querySelectorAll("[data-final]")].map(x=>x.checked);if(state.checklist.every(Boolean))state.completed.checklist=true;save();alert(state.checklist.every(Boolean)?"チェックシートを完了しました。":"未確認の項目があります。")}}
  function render(name){renderNav(name);if(name==="home")home();if(name==="learn")learn();if(name==="exercises")exerciseList();if(name==="quiz")quizView();if(name==="checklist")checklist();lucide.createIcons()};render("home");
})();
