(() => {
  if (Number(new URLSearchParams(location.search).get("module")) !== 4) return;

  const key = "designResearchPracticeModuleProgress";
  const state = JSON.parse(localStorage.getItem(key) || "{}");
  state.done ||= {}; state.answers ||= {}; state.prep ||= {}; state.history ||= []; state.quiz ||= {};
  const practices = [
    ["簡易システム構成設計", "予約管理システムを例に、要件を満たす構成案と確認観点を整理します。"],
    ["API設計レビュー", "注文APIの設計案を確認し、入力・認証・エラー・変更影響の観点を追加します。"],
    ["既存システム影響調査", "認証方式を変更する場合の影響範囲と追加確認事項を整理します。"],
    ["設計書レビュー", "AIが作成した設計書の不足、曖昧な表現、過剰な提案を確認します。"],
    ["技術選定", "要件に対して複数の候補を比較し、採用理由とリスクを説明します。"],
    ["障害原因の仮説整理", "ログと状況から仮説を分け、確定前に必要な確認を整理します。"]
  ];
  const sections = [["home","モジュール概要","layout-dashboard"],["theory","基礎知識","book-open"],["prep","実習前整理","clipboard-pen-line"],["list","実習一覧","list-checks"],["compare","設計比較","git-compare-arrows"],["history","修正履歴","history"],["memo","設計メモ","file-pen-line"],["final","総合課題","flag"],["quiz","総合テスト","circle-check"],["results","学習結果","chart-no-axes-column"],["terms","用語集","library-big"]];
  document.title = "実務演習1：設計・調査 | AI業務活用研修";
  document.body.innerHTML = `<div class="m1-page"><header class="m1-header"><a class="m1-brand" href="index.html"><i data-lucide="graduation-cap"></i>AI業務活用研修</a><span class="m1-header-title">MODULE 04　実務演習1：設計・調査</span><div class="m1-header-actions"><span><i data-lucide="cloud-check"></i> 自動保存</span><span>受講生A</span><span class="m1-avatar">A</span></div></header><div class="m1-shell"><aside class="m1-sidebar"><div class="m1-progress-label"><span>モジュール進捗</span><b id="progress">0%</b></div><div class="m1-progress"><span id="bar"></span></div><div class="m4-mini" id="counts"></div><nav class="m1-nav" id="nav"></nav></aside><main class="m1-main"><div class="m1-view" id="view"></div></main></div></div>`;
  const view = document.getElementById("view"), nav = document.getElementById("nav");
  const save = () => { localStorage.setItem(key, JSON.stringify(state)); progress(); };
  const status = id => state.done[id] ? `<span class="m4-status complete"><i data-lucide="check"></i>完了</span>` : `<span class="m4-status">未着手</span>`;
  function progress() { const complete = Object.keys(state.done).length, total = practices.length + 6, pct = Math.min(100, Math.round(complete / total * 100)); document.getElementById("progress").textContent = `${pct}%`; document.getElementById("bar").style.width = `${pct}%`; document.getElementById("counts").textContent = `完了 ${complete}件 / 未完了 ${Math.max(0,total-complete)}件`; }
  function menu(active) { nav.innerHTML = sections.map(([id,label,icon]) => `<button class="${active===id?"active":""} ${state.done[id]?"done":""}" data-view="${id}"><i data-lucide="${state.done[id]?"check-circle-2":icon}"></i>${label}</button>`).join(""); nav.querySelectorAll("button").forEach(b => b.onclick = () => render(b.dataset.view)); progress(); lucide.createIcons(); }
  function actions(next, back) { return `<div class="m1-actions">${back?`<button class="m1-secondary" data-go="${back}"><i data-lucide="arrow-left"></i> 前へ</button>`:""}<button class="m1-primary" data-go="${next}">次へ <i data-lucide="arrow-right"></i></button></div>`; }
  function bindGo() { view.querySelectorAll("[data-go]").forEach(b => b.onclick = () => render(b.dataset.go)); }
  function home() { view.innerHTML = `<p class="m1-kicker">MODULE 04</p><h1 class="m1-title">実務演習1：設計・調査</h1><p class="m1-lead">AIが作成した設計案を検証し、修正理由を説明できるようになる</p><section class="m1-card"><h2>目的</h2><p>AIを活用して設計・調査業務を支援し、AIが生成した内容をそのまま使用せず、確認、検証、修正する力を身につけます。</p><p>この実習では、AIを設計者の代わりとして使用するのではなく、設計案、調査観点、比較候補を作成する補助ツールとして利用します。</p><p>最終的な設計内容と判断については、受講者自身が説明責任を持つことを目的とします。</p></section><section class="m1-card" style="margin-top:14px"><h2>学習の進め方</h2><ol class="m1-task-list"><li>自分で考える</li><li>AIに案を作成させる</li><li>AI出力を確認する</li><li>誤りと不足を修正する</li><li>修正理由を記録する</li><li>最終判断を人間が行う</li></ol></section><div class="m4-summary"><section class="m1-card"><div class="m1-stat">6</div><p>実務演習</p></section><section class="m1-card"><div class="m1-stat">1</div><p>設計メモ</p></section><section class="m1-card"><div class="m1-stat">5</div><p>総合テスト問題</p></section></div>${actions("theory")}`; bindGo(); }
  function theory() { view.innerHTML = `<p class="m1-kicker">THEORY</p><h1 class="m1-title">基礎知識</h1><div class="m1-concepts"><section class="m1-card m1-concept"><strong>AIが支援できること</strong><p>設計案候補、要件整理、不足観点、構成比較、API項目の下書き、リスク候補、レビュー観点、調査要約、技術比較表の作成。</p></section><section class="m1-card m1-concept"><strong>AIに任せてはいけないこと</strong><p>要件の最終確定、顧客要望の解釈確定、設計の最終承認、本番変更の実施、セキュリティ例外の判断。</p></section></div><section class="m1-card" style="margin-top:14px"><h2>設計・調査で確認する観点</h2><table class="m4-table"><tr><th>観点</th><th>確認内容</th></tr><tr><td>正確性</td><td>要件、公式仕様、前提条件と矛盾していないか</td></tr><tr><td>要件適合</td><td>性能、可用性、セキュリティ、運用要件を満たすか</td></tr><tr><td>完全性</td><td>認証、例外、監視、バックアップ、障害時対応が欠けていないか</td></tr><tr><td>実現可能性</td><td>予算、期限、既存環境、スキルで実行できるか</td></tr><tr><td>リスク</td><td>単一障害点、情報漏えい、変更影響、運用負荷を説明できるか</td></tr></table></section><div class="m1-warning">AI出力は設計の候補です。要件資料、公式ドキュメント、既存構成、関係者レビューで必ず検証してください。</div>${actions("prep","home")}`; bindGo(); }
  function prep() { const p=state.prep; view.innerHTML = `<p class="m1-kicker">PREPARATION</p><h1 class="m1-title">実習前整理</h1><p class="m1-lead">AIに依頼する前の自分の考えを残します。AI出力と比較するため、保存後も最初の方針は残してください。</p><section class="m1-card"><div class="m1-field"><label>初期設計方針</label><textarea id="policy" placeholder="例：可用性を優先し、認証・監視・バックアップを最初から設計に含める">${p.policy||""}</textarea></div><div class="m1-field"><label>調査観点</label><textarea id="points" placeholder="例：要件適合、既存システム影響、セキュリティ、運用負荷、費用">${p.points||""}</textarea></div><div class="m1-field"><label>現時点で重要だと考える課題</label><textarea id="issues" placeholder="例：単一障害点、個人情報の扱い、変更時の影響範囲">${p.issues||""}</textarea></div><div class="m1-actions"><button class="m1-primary" id="saveprep">初期方針を保存する</button></div></section>${actions("list","theory")}`; bindGo(); document.getElementById("saveprep").onclick=()=>{ const policy=document.getElementById("policy").value.trim(),points=document.getElementById("points").value.trim(),issues=document.getElementById("issues").value.trim(); if(!policy||!points||!issues){alert("3つの項目をすべて記入してください。");return;} state.prep={policy,points,issues};state.done.prep=true;state.history.push({date:new Date().toLocaleString("ja-JP"),title:"実習前の初期方針を保存",note:"AI出力との比較基準を記録しました。"});save();alert("初期方針を保存しました。設計比較画面でAI案と比較できます。");}; }
  function list() { view.innerHTML = `<p class="m1-kicker">PRACTICE</p><h1 class="m1-title">実習一覧</h1><div class="m1-exercises">${practices.map(([title,desc],i)=>`<article class="m1-exercise"><div class="m4-practice-meta"><small>実習 ${String(i+1).padStart(2,"0")}</small>${status(`ex${i}`)}</div><h3>${title}</h3><p>${desc}</p><p class="m4-mini">AIの候補を検証し、修正理由を記録します。</p><button class="m1-secondary" data-ex="${i}">実習を開く</button></article>`).join("")}</div>${actions("compare","prep")}`; bindGo(); view.querySelectorAll("[data-ex]").forEach(b=>b.onclick=()=>practice(+b.dataset.ex)); }
  function practice(i) { const [title,desc]=practices[i],a=state.answers[`ex${i}`]||{}; const sample=["Web/API/DBを分離し、認証・監視・バックアップを設ける案", "入力項目、認証、エラー形式、バージョン管理を整理する案", "利用中の認証、画面、API、データ、運用手順を確認する案", "目的、前提、例外、運用、障害時対応を追加する案", "費用、性能、運用性、既存環境との互換性で比較する案", "接続プール枯渇、遅いSQL、DB負荷を候補として提示する案"][i]; view.innerHTML=`<p class="m1-kicker">PRACTICE ${i+1} / 6</p><h1 class="m1-title">${title}</h1><section class="m1-card"><h2>シナリオ</h2><p>${desc}</p><div class="m1-ai"><div class="response-head"><span>AIの設計・調査案（学習用サンプル）</span><i data-lucide="sparkles"></i></div><p>${sample}</p><p class="m4-mini">これは候補であり、正しさを保証しません。要件・公式資料・既存構成と比較してください。</p></div><div class="m1-field"><label>自分の初期案・確認したい点</label><textarea id="initial" placeholder="AIを見る前に考えた方針、前提、確認事項を記入してください。">${a.initial||""}</textarea></div><div class="m1-field"><label>AI案の採用・修正・削除する内容</label><textarea id="review" placeholder="採用する内容、誤り、不足、過剰な提案を具体的に記入してください。">${a.review||""}</textarea></div><div class="m1-field"><label>最終判断と修正理由</label><textarea id="reason" placeholder="実務要件、根拠、影響範囲、人間が確認した内容を記入してください。">${a.reason||""}</textarea></div><label class="m4-check"><input type="checkbox" id="check" ${a.check?"checked":""}><span>AI出力をそのまま採用せず、根拠を確認して修正した</span></label><div class="m1-actions"><button class="m1-secondary" id="back">実習一覧へ戻る</button><button class="m1-primary" id="finish">実習を完了する</button></div></section>`; lucide.createIcons(); const saveDraft=()=>{state.answers[`ex${i}`]={initial:document.getElementById("initial").value,review:document.getElementById("review").value,reason:document.getElementById("reason").value,check:document.getElementById("check").checked};save();}; ["initial","review","reason"].forEach(id=>document.getElementById(id).oninput=saveDraft);document.getElementById("check").onchange=saveDraft;document.getElementById("back").onclick=list;document.getElementById("finish").onclick=()=>{const initial=document.getElementById("initial").value.trim(),review=document.getElementById("review").value.trim(),reason=document.getElementById("reason").value.trim(),check=document.getElementById("check").checked;if(!initial||!review||!reason||!check){alert("回答と確認チェックをすべて完了してください。");return;}state.answers[`ex${i}`]={initial,review,reason,check};state.done[`ex${i}`]=true;state.history.push({date:new Date().toLocaleString("ja-JP"),title:`実習${i+1}：${title}`,note:`修正理由：${reason.slice(0,80)}${reason.length>80?"…":""}`});save();alert("実習を完了しました。修正履歴にも記録しました。");}; }
  function compare() { const p=state.prep, completed=practices.filter((_,i)=>state.answers[`ex${i}`]), checks=state.compareChecks?.length?state.compareChecks:(state.done.compare?[true,true,true,true]:[]); view.innerHTML=`<p class="m1-kicker">COMPARE</p><h1 class="m1-title">設計比較</h1><p class="m1-lead">自分の初期方針、AIの候補、最終設計を比較し、変更理由を確認します。</p><div class="m4-compare"><section class="initial"><h3>自分の初期方針</h3><p>${p.policy||"未保存"}</p><h4>調査観点</h4><p>${p.points||"未保存"}</p></section><section class="ai"><h3>AIが提示する候補</h3><p>複数案、比較観点、リスク候補、レビュー項目を短時間で作成できます。</p><p>ただし、会社固有の要件や既存環境の制約を知らない場合があります。</p></section><section class="final"><h3>最終設計・調査結果</h3><p>${completed.length?completed.map((_,i)=>state.answers[`ex${i}`]?.reason).filter(Boolean).join("<br><br>"):"実習完了後に、ここへ最終判断が表示されます。"}</p></section></div><section class="m1-card" style="margin-top:14px"><h2>比較で確認すること</h2><label class="m4-check"><input type="checkbox" data-c="1" ${checks[0]?"checked":""}>要件にない前提をAIが追加していないか</label><label class="m4-check"><input type="checkbox" data-c="2" ${checks[1]?"checked":""}>セキュリティ、運用、障害時対応が不足していないか</label><label class="m4-check"><input type="checkbox" data-c="3" ${checks[2]?"checked":""}>過剰な構成や不要な技術提案を採用していないか</label><label class="m4-check"><input type="checkbox" data-c="4" ${checks[3]?"checked":""}>変更理由を第三者に説明できるか</label><div class="m1-actions"><button class="m1-primary" id="compareDone">比較を完了する</button></div></section>${actions("history","list")}`; bindGo();document.getElementById("compareDone").onclick=()=>{const selected=[...view.querySelectorAll("[data-c]")].map(x=>x.checked);if(selected.some(x=>!x)){alert("すべての比較項目を確認してください。");return;}state.compareChecks=selected;state.done.compare=true;save();alert("設計比較を完了しました。");}; }
  function history() { const historyItems = state.history.length ? state.history.slice().reverse().map(x=>`<article class="m4-history-item"><time>${x.date}</time><strong>${x.title}</strong><p>${x.note}</p></article>`).join("") : "<p class=\"m4-mini\">まだ履歴がありません。実習または設計メモを保存すると履歴が表示されます。</p>"; view.innerHTML=`<p class="m1-kicker">HISTORY</p><h1 class="m1-title">修正履歴</h1><p class="m1-lead">AI案の採用・修正・削除と、その理由を残します。</p><section class="m1-card"><h2>保存済みの修正履歴</h2><div class="m4-history">${historyItems}</div></section><section class="m1-card" style="margin-top:14px"><div class="m1-field"><label>手動で履歴を追加</label><input id="historyTitle" placeholder="例：認証方式の前提を修正"></div><div class="m1-field"><label>修正理由</label><textarea id="historyNote" placeholder="要件・公式資料・既存環境との比較結果を記入してください。"></textarea></div><button class="m1-secondary" id="addHistory">履歴を追加</button></section>${actions("memo","compare")}`; bindGo();document.getElementById("addHistory").onclick=()=>{const title=document.getElementById("historyTitle").value.trim(),note=document.getElementById("historyNote").value.trim();if(!title||!note){alert("修正内容と理由を記入してください。");return;}state.history.push({date:new Date().toLocaleString("ja-JP"),title,note});state.done.history=true;save();history();}; }
  function memo() { const m=state.answers.memo||{}; const fields=[["project","対象システム・目的"],["initial","初期設計"],["request","AIへの依頼内容"],["output","AI出力の要約"],["changes","変更した内容"],["added","追加した観点"],["removed","削除した提案"],["final","最終設計・最終判断"],["rationale","最終判断の根拠"],["use","AIを有効に使えた点"],["check","人間による最終確認事項"]];view.innerHTML=`<p class="m1-kicker">DESIGN MEMO</p><h1 class="m1-title">設計メモ</h1><p class="m1-lead">提出可能な設計メモとして、AI利用と人間の判断を整理します。</p><section class="m1-card">${fields.map(([id,label])=>`<div class="m1-field"><label>${label}</label><textarea id="memo-${id}" placeholder="${label}を記入してください。">${m[id]||""}</textarea></div>`).join("")}<div class="m1-actions"><button class="m1-secondary" id="exportMemo">JSON出力</button><button class="m1-primary" id="saveMemo">設計メモを保存する</button></div></section>${actions("final","history")}`; bindGo();document.getElementById("saveMemo").onclick=()=>{const data={};fields.forEach(([id])=>data[id]=document.getElementById(`memo-${id}`).value.trim());if(Object.values(data).some(x=>!x)){alert("設計メモのすべての項目を記入してください。");return;}state.answers.memo=data;state.done.memo=true;state.history.push({date:new Date().toLocaleString("ja-JP"),title:"設計メモを保存",note:"最終設計とAI利用の判断理由を記録しました。"});save();alert("設計メモを保存しました。");};document.getElementById("exportMemo").onclick=()=>download("design-memo.json",state.answers.memo||{}); }
  function finalTask() { const a=state.answers.final||{};view.innerHTML=`<p class="m1-kicker">FINAL TASK</p><h1 class="m1-title">総合課題</h1><p class="m1-lead">小規模な会員制Webシステムを題材に、AIを補助として使いながら設計・調査結果をまとめます。</p><section class="m1-card"><div class="m4-final-step"><b>1</b><div><strong>自分の設計方針を作る</strong><p class="m4-mini">可用性、認証、データ保護、監視、バックアップを含めます。</p></div></div><div class="m4-final-step"><b>2</b><div><strong>AIに構成案と確認観点を依頼する</strong><p class="m4-mini">入力に機密情報を含めないでください。</p></div></div><div class="m4-final-step"><b>3</b><div><strong>AI案を比較・修正する</strong><p class="m4-mini">不足・誤り・過剰な提案と、修正理由を記録します。</p></div></div><div class="m4-final-step"><b>4</b><div><strong>設計メモとして最終判断を提出する</strong><p class="m4-mini">最終承認は人間が行います。</p></div></div><div class="m1-field"><label>最終課題の設計方針と判断理由</label><textarea id="finalAnswer" placeholder="要件、AI案の検証結果、最終判断、残るリスクを記入してください。">${a.text||""}</textarea></div><label class="m4-check"><input id="finalCheck" type="checkbox" ${a.check?"checked":""}>AI出力を検証し、最終判断は自分が行った</label><div class="m1-actions"><button class="m1-primary" id="finishFinal">総合課題を完了する</button></div></section>${actions("quiz","memo")}`;bindGo();document.getElementById("finishFinal").onclick=()=>{const text=document.getElementById("finalAnswer").value.trim(),check=document.getElementById("finalCheck").checked;if(!text||!check){alert("回答と確認チェックを完了してください。");return;}state.answers.final={text,check};state.done.final=true;save();alert("総合課題を完了しました。");}; }
  function quiz() { const qs=[["設計業務でAIの役割として適切なのはどれですか。",["候補案を作り人間が検証する","最終要件を確定する","本番変更を自動実行する"],0],["AI案をレビューする際に確認すべき点はどれですか。",["要件・前提・リスク・実現可能性","文章の長さだけ","AIが自信を持っているか"],0],["AI出力の修正理由を記録する主な目的はどれですか。",["最終判断を説明できるようにする","AIを評価しないため","入力時間を増やすため"],0],["技術選定で最終的に人間が判断すべきことはどれですか。",["要件に合う採用案と責任","候補一覧の作成","比較表の下書き"],0],["障害原因の仮説について正しい説明はどれですか。",["確認前は候補であり確定原因ではない","AIが出した時点で確定する","最初の仮説以外は不要"],0]];let n=state.quiz.n||0;if(state.quiz.score!==undefined){const pass=state.quiz.score>=4;view.innerHTML=`<p class="m1-kicker">QUIZ RESULT</p><h1 class="m1-title">総合テスト結果</h1><section class="m1-result ${pass?"":"fail"}"><h2>${state.quiz.score} / 5</h2><p>${pass?"合格です。AIを補助として利用し、検証と最終判断を人間が行う基本を理解できています。":"再学習推奨です。基礎知識と設計比較を見直してから再受験してください。"}</p>${!pass?`<button class="m1-primary" id="retry">再受験する</button>`:""}</section>`;if(!pass)document.getElementById("retry").onclick=()=>{state.quiz={};save();quiz();};return;}view.innerHTML=`<p class="m1-kicker">QUIZ ${n+1} / 5</p><h1 class="m1-title">総合テスト</h1><section class="m1-quiz-card"><h3>${qs[n][0]}</h3>${qs[n][1].map((x,i)=>`<label class="m1-option"><input type="radio" name="q" value="${i}">${x}</label>`).join("")}<div class="m1-actions"><button class="m1-primary" id="nextQuiz">${n===4?"採点する":"次へ"}</button></div></section>`;document.getElementById("nextQuiz").onclick=()=>{const selected=view.querySelector("input:checked");if(!selected){alert("回答を選択してください。");return;}state.quiz.answers ||= [];state.quiz.answers[n]=+selected.value;if(n<4){state.quiz.n=n+1;}else{state.quiz.score=state.quiz.answers.reduce((sum,a,i)=>sum+(a===qs[i][2]?1:0),0);if(state.quiz.score>=4)state.done.quiz=true;}save();quiz();}; }
  function results() { const completed=practices.filter((_,i)=>state.done[`ex${i}`]).length;view.innerHTML=`<p class="m1-kicker">RESULTS</p><h1 class="m1-title">学習結果</h1><div class="m4-summary"><section class="m1-card"><div class="m1-stat">${completed}/6</div><p>完了実習</p></section><section class="m1-card"><div class="m1-stat">${state.history.length}</div><p>修正履歴</p></section><section class="m1-card"><div class="m1-stat">${state.quiz.score??"-"}/5</div><p>総合テスト</p></section></div><section class="m1-card"><h2>到達目標チェック</h2>${["AIを設計補助ツールとして利用できる","AIを使用する前に自分の設計方針を整理できる","AI出力の問題点を発見・修正できる","技術選定と変更影響の理由を説明できる","最終設計に対して説明責任を持てる"].map((x,i)=>`<p>${(completed>=5&&state.done.memo&&state.quiz.score>=4)||state.done.final?"✓":"○"} ${x}</p>`).join("")}<div class="m1-actions"><button class="m1-secondary" id="reset">このモジュールをリセット</button></div></section>`;document.getElementById("reset").onclick=()=>{if(confirm("第4モジュールの回答、履歴、テスト結果をすべて削除します。よろしいですか。")){localStorage.removeItem(key);location.reload();}}; }
  function terms() { view.innerHTML=`<p class="m1-kicker">GLOSSARY</p><h1 class="m1-title">用語集</h1><section class="m1-card"><dl class="l2-glossary"><dt>設計案</dt><dd>要件を満たすための構成・処理・運用の候補。</dd><dt>影響調査</dt><dd>変更が画面、API、データ、運用、利用者に与える影響を確認すること。</dd><dt>技術選定</dt><dd>要件、費用、性能、運用性、リスクを比較して採用技術を決めること。</dd><dt>修正履歴</dt><dd>設計内容を変更した理由、根拠、判断者を記録すること。</dd><dt>説明責任</dt><dd>最終判断の理由と確認方法を関係者へ説明できる責任。</dd></dl></section>`; }
  function download(name,data) { const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),0); }
  function render(id) { menu(id); ({home,theory,prep,list,compare,history,memo,final:finalTask,quiz,results,terms}[id])(); lucide.createIcons(); }
  render("home");
})();
