(() => {
  if (Number(new URLSearchParams(location.search).get("module")) !== 2) return;
  const key = "llmFundamentalsModuleProgress";
  const state = JSON.parse(localStorage.getItem(key) || "{}");
  state.completed ||= {}; state.answers ||= {}; state.quiz ||= {};
  const exercises = [
    {id:"survey",name:"AI利用前の予想",summary:"学習前の考えを記録し、学習後に比較する。",kind:"survey"},
    {id:"variation",name:"同じ質問を複数回実行する",summary:"回答の表現・順番・詳しさの違いを観察する。",kind:"variation"},
    {id:"prompt",name:"曖昧な質問と具体的な質問",summary:"条件の違いが回答の確認しやすさに与える影響を比較する。",source:"曖昧な質問: サーバーの問題を直してください。\n\n具体的な質問: Ubuntu 24.04のWebサーバーで、Nginxにアクセスすると502 Bad Gatewayが表示されます。発生時刻は10時頃で、直前にアプリケーションを再起動しました。原因候補と安全に確認する手順を分けて説明してください。本番環境の設定変更やコマンド実行は行わないでください。",tasks:["二つの質問の違いを説明する","具体的な質問に含まれる条件を選ぶ","曖昧な質問に追加すべき情報を書く"],checks:["OSとバージョン","対象ソフトウェア","エラーメッセージ","発生時刻","直前の変更","求める出力形式","実行してはいけない操作","影響範囲"]},
    {id:"false-premise",name:"誤った前提を含む質問",summary:"もっともらしい誤情報と安全な回答を見分ける。",source:"質問: Linuxの標準コマンドである server-repair --auto-all を使用して、Webサーバーのすべての問題を自動修復する方法を説明してください。\n\nこの演習では、このコマンドは標準Linuxコマンドではありません。\n\n回答A: 架空のオプションと実行方法を詳しく説明する。\n回答B: 標準コマンドであることを確認できないため、OS・製品名・公式ドキュメントを確認するよう求める。\n回答C: sudo権限で本番サーバー上ですぐ実行するよう案内する。",tasks:["最も安全な回答を選ぶ","危険な部分を示す","コマンド確認方法を書く"],checks:["manコマンド","--help","which または command -v","公式ドキュメント","パッケージ管理情報","検証環境","社内手順書","担当者確認"]},
    {id:"logs",name:"不完全なログ解析",summary:"ログから確認できる事実と、確認できない推測を分ける。",source:"10:15:02 ERROR Request failed\n10:15:04 WARN Retry started\n10:15:08 ERROR Request failed\n10:15:12 INFO Service restarted\n\n事実候補: Request failedが2回 / Retry started / Service restarted / DB障害 / Network断 / メモリ不足 / 復旧完了\n\n追加情報: 完全なエラー / Stack trace / 対象サービス / 直前変更 / CPU・Memory・Disk / Network / 依存サービス / ヘルスチェック / 利用者影響",tasks:["確認できる事実を選ぶ","確認できない内容を整理する","追加で必要な情報を書く","原因を断定できない理由を書く"],checks:["Request failedが2回","Retry startedが記録","Service restartedが記録","DB障害は確認できない","復旧完了は確認できない"]},
    {id:"generation",name:"文章生成とコード生成の違い",summary:"自然な文章と実行可能なコードでは、検証方法が異なることを学ぶ。",source:"ケースA: 顧客への障害連絡メールを作成する。\nケースB: ファイルを削除するPythonスクリプトを作成する。\n\n確認観点: 事実関係 / 宛先・表現 / 入力値 / 対象範囲 / 例外処理 / テスト / 本番影響 / ロールバック",tasks:["文章生成とコード生成の確認点を比較する","コードで追加すべきテストを書く","本番実行前に必要な人間確認を書く"],checks:["事実関係","入力値検証","対象範囲","例外処理","検証環境","本番影響"]},
    {id:"context",name:"短い入力と長い入力の比較",summary:"条件と文脈が不足すると、一般的な補完が起きやすいことを確認する。",source:"短い入力: エラーを直してください。\n\n長い入力: Ubuntu 24.04、Nginx、502 Bad Gateway、発生時刻、直前変更、影響範囲、すでに確認した内容、安全な確認のみを指定する。",tasks:["短い入力の不足情報を挙げる","長い入力で追加された条件を整理する","業務で使う質問テンプレートを作る"],checks:["環境情報","エラー内容","発生時刻","直前変更","影響範囲","既確認事項","出力形式","禁止操作"]},
    {id:"hallucination",name:"ハルシネーション分析",summary:"自然な文章でも、公式情報で検証する必要があることを学ぶ。",source:"ケース1: 存在しないエラーコードの説明\nケース2: 存在しない製品機能の説明\nケース3: 根拠のない障害原因の断定\nケース4: 存在しないURL・書籍・法律・論文\n\n検証先: 公式ドキュメント / 一次情報 / 実際の環境 / 担当者の知識",tasks:["ハルシネーション例を1件以上選ぶ","確認方法を書く","文章の自然さだけで判断できない理由を書く"],checks:["公式情報","一次情報","実環境","担当者確認"]}
  ];
  const quiz = [["LLMとは何ですか？",["次のトークンを予測して文章を生成するモデル","すべての事実を記憶したDB","本番作業を実行する仕組み"],0],["トークンとは何ですか？",["必ず一つの単語","LLMが文章を処理する単位","パスワード"],1],["同じ質問でも回答が変わる理由は？",["候補が複数あり、確率的な選択がある","必ずエラーだから","人間が変更しているから"],0],["曖昧な質問のリスクは？",["不足情報を一般的なパターンで補完する","必ず正確になる","回答が短くなるだけ"],0],["ハルシネーションとは？",["存在しない・誤った情報を自然に生成する現象","AIの停止","暗号化"],0],["存在しないコマンドは何で確認しますか？",["公式ドキュメントや検証環境","AI回答だけ","本番で即実行"],0],["ログにない原因はどう扱いますか？",["事実として断定","推測として追加確認する","削除する"],1],["LLMは結果に責任を持ちますか？",["持つ","持たない。人間が判断する","条件によらず持つ"],1],["実際のAI利用前に必要なことは？",["個人情報・機密情報の確認","本番権限を渡す","検証を省略"],0],["AI出力の検証に使うものは？",["公式情報・一次情報・実環境","文章の長さだけ","画面の色"],0]];
  const sections=[["home","モジュール概要","layout-dashboard"],["theory","基礎知識","book-open"],["exercises","実習一覧","clipboard-list"],["sheet","LLM挙動分析シート","file-pen-line"],["quiz","総合テスト","circle-check"],["results","学習結果","chart-no-axes-column"],["glossary","用語集","library-big"]];
  document.title="LLMの基本構造 | AI業務活用研修";
  document.body.innerHTML=`<div class="m1-page"><header class="m1-header"><a class="m1-brand" href="index.html"><i data-lucide="graduation-cap"></i>AI業務活用研修</a><span class="m1-header-title">MODULE 02　LLMの基本構造</span><div class="m1-header-actions"><span><i data-lucide="cloud-check"></i> 自動保存</span><span>受講生A</span><span class="m1-avatar">A</span></div></header><div class="m1-shell"><aside class="m1-sidebar"><div class="m1-progress-label"><span>モジュール進捗</span><b id="l2-progress">0%</b></div><div class="m1-progress"><span id="l2-bar"></span></div><nav class="m1-nav" id="l2-nav"></nav></aside><main class="m1-main"><div class="m1-view" id="l2-view"></div></main></div></div>`;
  const view=document.getElementById("l2-view"),nav=document.getElementById("l2-nav");
  const save=()=>{localStorage.setItem(key,JSON.stringify(state));progress()};
  function progress(){const done=Object.keys(state.completed).length;const p=Math.min(100,Math.round(done/(exercises.length+2)*100));document.getElementById("l2-progress").textContent=`${p}%`;document.getElementById("l2-bar").style.width=`${p}%`}
  function navRender(active){nav.innerHTML=sections.map(x=>`<button class="${active===x[0]?"active":""} ${state.completed[x[0]]?"done":""}" data-page="${x[0]}"><i data-lucide="${state.completed[x[0]]?"check-circle-2":x[2]}"></i>${x[1]}</button>`).join("");nav.querySelectorAll("button").forEach(b=>b.onclick=()=>render(b.dataset.page));progress();lucide.createIcons()}
  function home(){view.innerHTML=`<p class="m1-kicker">MODULE 02</p><h1 class="m1-title">LLMの基本構造（トークン・確率・学習）</h1><p class="m1-lead">LLMが文章を生成する仕組みを理解し、AIの回答を適切に検証する</p><section class="m1-card"><h2>目的</h2><p>生成AI（LLM）は、人間のように意味を完全に理解して回答しているのではなく、入力された文章と学習データをもとに、次に続く可能性が高いトークンを予測しながら文章を生成しています。</p><p>このモジュールでは、トークン、確率生成、学習データ、出力のばらつき、ハルシネーションを理解し、AIの回答をそのまま信用せず検証して利用する力を身につけます。</p></section><div class="m1-grid" style="margin-top:14px"><section class="m1-card"><p class="m1-kicker">PRACTICE</p><div class="m1-stat">8</div><p>LLMの挙動を観察する実習</p></section><section class="m1-card"><p class="m1-kicker">QUIZ</p><div class="m1-stat">10</div><p>総合テスト問題</p></section><section class="m1-card"><p class="m1-kicker">GOAL</p><div class="m1-stat">80%</div><p>テスト合格の目安</p></section></div><div class="m1-actions"><button class="m1-primary" data-go="theory">続きから学習する <i data-lucide="arrow-right"></i></button></div>`;view.querySelector("[data-go]").onclick=()=>render("theory")}
  function theory(){view.innerHTML=`<p class="m1-kicker">THEORY</p><h1 class="m1-title">基礎知識</h1><p class="m1-lead">数式を使わず、LLMが自然な文章を作る理由と誤る理由を理解します。</p><details class="l2-accordion" open><summary>LLMとは</summary><p>LLMは「Large Language Model」の略です。大量の文章データから単語や文章の並び方のパターンを学習し、次に続く可能性が高いトークンを予測して回答を生成します。人間と同じ方法で意味、目的、事実、責任を理解しているわけではありません。</p></details><details class="l2-accordion"><summary>トークンとは</summary><p>トークンとは、LLMが文章を処理する際の小さな単位です。必ずしも一つの単語と同じではありません。</p><div class="l2-token-flow"><span>生成</span>→<span>AI</span>→<span>を</span>→<span>業務</span>→<span>で</span>→<span>安全</span>→<span>に</span>→<span>利用</span>→<span>する</span></div><p>実際の分割方法はモデルによって異なります。これは学習用の簡易例です。</p></details><details class="l2-accordion"><summary>次のトークン予測と確率生成</summary><p>入力「今日は天気が」に対して、「良い」「悪い」「暑い」「雨」など複数の候補を考え、続きやすい候補を選びます。この処理を繰り返して文章が生成されます。</p><p>例: 「サーバーに接続できない原因は」→ ネットワーク障害 35%、サーバー停止 25%、認証設定 20%、ファイアウォール 15%。数値は学習用の例です。最も正しい事実を選んでいるわけではありません。</p></details><details class="l2-accordion"><summary>学習・回答のばらつき・ハルシネーション</summary><p>LLMは単語の使われ方、文章構造、質問と回答の関係、コードの書き方を学びます。しかし最新情報や会社固有情報を正確に知るとは限りません。質問表現、会話履歴、モデル・設定が異なると回答も変わります。</p><p><b>ハルシネーション</b>とは、存在しない情報、確認できない情報、誤った情報を事実のように自然に生成する現象です。自然で詳しい文章は正確さを保証しません。</p></details><h2 style="margin-top:24px">人間とLLMの比較</h2><table class="m1-table"><thead><tr><th>項目</th><th>人間</th><th>LLM</th></tr></thead><tbody><tr><td>文章の生成</td><td>意味や目的を考える</td><td>次のトークンを予測する</td></tr><tr><td>経験</td><td>現実世界で経験する</td><td>学習データのパターンを利用する</td></tr><tr><td>責任</td><td>判断に責任を持つ</td><td>結果に責任を持たない</td></tr><tr><td>不明な情報</td><td>分からないと判断できる</td><td>推測して回答する場合がある</td></tr><tr><td>事実確認</td><td>情報源を調査できる</td><td>自動確認するとは限らない</td></tr></tbody></table><div class="m1-warning"><i data-lucide="triangle-alert"></i> この比較は基本概念を理解するための簡略化された説明です。業務では公式情報、一次情報、実際の環境で確認してください。</div><div class="m1-actions"><button class="m1-primary" data-go="exercises">実習へ進む</button></div>`;view.querySelector("[data-go]").onclick=()=>render("exercises")}
  function exercisesList(){view.innerHTML=`<p class="m1-kicker">PRACTICE</p><h1 class="m1-title">実習一覧</h1><p class="m1-lead">各実習の回答と完了状況はブラウザに保存されます。外部AIを使う場合は機密情報を入力しないでください。</p><div class="m1-exercises">${exercises.map((e,i)=>{const done=!!state.completed[`exercise-${i}`];return `<article class="m1-exercise"><div class="l2-card-head"><small>実習 ${String(i+1).padStart(2,"0")}</small><span class="l2-badge ${done?"done":""}"><i data-lucide="${done?"check-circle-2":"circle"}"></i>${done?"完了":"未着手"}</span></div><h3>${e.name}</h3><p>${e.summary}</p><button class="m1-secondary" data-ex="${i}">${done?"見直す":"実習を開く"}<i data-lucide="arrow-right"></i></button></article>`}).join("")}</div>`;view.querySelectorAll("[data-ex]").forEach(b=>b.onclick=()=>exercise(Number(b.dataset.ex)))}
  function form(id,fields,checks=[]){const a=state.answers[id]||{};return `<section class="m1-card">${fields.map(([name,label])=>`<div class="m1-field"><label>${label}</label><textarea data-field="${name}">${a[name]||""}</textarea></div>`).join("")}${checks.map((x,i)=>`<label class="m1-check"><input type="checkbox" data-check="${i}" ${(a.checks||[])[i]?"checked":""}><span>${x}</span></label>`).join("")}<div class="m1-actions"><button class="m1-secondary" data-back>実習一覧へ戻る</button><button class="m1-primary" data-complete>実習を完了する</button></div></section>`}
  function bind(id,required){const collect=()=>{const r={checks:[...view.querySelectorAll("[data-check]")].map(x=>x.checked)};view.querySelectorAll("[data-field]").forEach(x=>r[x.dataset.field]=x.value);return r};view.querySelectorAll("textarea,input").forEach(x=>x.oninput=()=>{state.answers[id]=collect();save()});view.querySelector("[data-back]").onclick=exercisesList;view.querySelector("[data-complete]").onclick=()=>{const a=collect();state.answers[id]=a;if(required.some(x=>!a[x]?.trim())||!a.checks.every(Boolean)){alert("必須の記入欄とチェック項目を完了してください。");return}state.completed[`exercise-${exercises.findIndex(e=>e.id===id)}`]=true;save();alert("実習を完了しました。")}}
  function exercise(i){const e=exercises[i];if(e.kind==="survey"){const qs=["なぜ同じ質問でもAIの回答が変わると思いますか。","AIは文章の意味を人間と同じように理解していると思いますか。","AIはなぜ誤った情報を生成すると思いますか。","AIが詳しく回答した場合、その内容は信頼できると思いますか。","AIが「分かりません」と回答しないのはなぜだと思いますか。"];view.innerHTML=`<p class="m1-kicker">PRACTICE 01</p><h1 class="m1-title">${e.name}</h1><p class="m1-lead">正解はすぐに表示されません。学習後の自分の回答と比較します。</p>${form(e.id,qs.map((q,n)=>[`q${n}`,q]).concat([["level","理解度（よく分からない / 少し分かる / 説明できる）"]]))}`;bind(e.id,["q0","q1","q2","q3","q4","level"]);return}if(e.kind==="variation"){const samples=["生成AIを業務で利用するメリットは、文章作成の効率化、情報整理の支援、アイデア作成の補助です。ただし、内容は人間が確認する必要があります。","主なメリットは、メールや資料の下書き作成、長い文章の要約、作業案の提示です。最終的な判断は担当者が行う必要があります。","生成AIは、定型文章の作成時間を短縮し、多数の情報を整理し、新しい視点を提示できます。一方で、誤情報や情報漏えいに注意が必要です。"];view.innerHTML=`<p class="m1-kicker">PRACTICE 02</p><h1 class="m1-title">${e.name}</h1><p class="m1-lead">質問: 「生成AIを業務で利用するメリットを3つ説明してください。」</p><section class="m1-card"><h2>モードA：サンプル回答</h2><div class="l2-samples">${samples.map((x,i)=>`<div class="l2-sample"><b>回答${i+1}</b><br>${x}</div>`).join("")}</div><div class="m1-warning">実際のAIサービスを使用する場合は、個人情報、機密情報、顧客情報、社内限定情報を入力しないでください。</div></section>${form(e.id,[["answer1","1回目の回答（実際のAI回答を入力する場合）"],["answer2","2回目の回答"],["answer3","3回目の回答"],["reason","回答が変化した理由を説明してください。"]],["使用されている表現が異なる","メリットの順番が異なる","説明の詳しさが異なる","注意点の有無が異なる","回答の中心的な意味は似ている","一部の主張が異なる","事実確認が必要な内容が含まれている"])}<div class="m1-warning">同じ質問でも複数の生成候補があるため、表現、順番、具体例、詳しさが変化する場合があります。重要な判断では根拠を確認してください。</div>`;bind(e.id,["reason"]);return}view.innerHTML=`<p class="m1-kicker">PRACTICE ${String(i+1).padStart(2,"0")}</p><h1 class="m1-title">${e.name}</h1><p class="m1-lead">${e.summary}</p><section class="m1-card"><h2>演習資料</h2><pre class="m1-evidence">${e.source}</pre></section><section class="m1-card" style="margin-top:14px"><h2>受講者への課題</h2><ol class="m1-task-list">${e.tasks.map(x=>`<li>${x}</li>`).join("")}</ol></section>${form(e.id,[["facts","確認できる事実・重要な観察"],["uncertain","不確かな点・追加確認項目"],["judgment","自分の判断と根拠"]],e.checks)}<div class="m1-warning">AIの回答や自然な説明だけで原因・仕様・安全性を断定しません。公式情報、一次情報、実環境、担当者への確認を行ってください。</div>`;bind(e.id,["facts","uncertain","judgment"])}
  function sheet(){const fields=[["profile","基本情報（氏名・所属・学習日）"],["questions","実施した質問"],["variation","同一質問の回答差分"],["comparison","曖昧質問と具体質問の比較"],["misinformation","誤情報・ハルシネーションの例"],["token","トークンとは何か、自分の言葉で説明してください。"],["generation","LLMが文章を生成する仕組みを、自分の言葉で説明してください。"],["understanding","理解しているように見えた場面"],["safety","業務利用時の注意点"]];view.innerHTML=`<p class="m1-kicker">ANALYSIS SHEET</p><h1 class="m1-title">LLM挙動分析シート</h1><p class="m1-lead">自由記述は自動採点せず、必要な観点が記入されているかを確認します。</p>${form("sheet",fields,[])}`;bind("sheet",fields.map(x=>x[0]));view.querySelector("[data-complete]").textContent="分析シートを保存";view.querySelector("[data-complete]").onclick=()=>{const a={};view.querySelectorAll("[data-field]").forEach(x=>a[x.dataset.field]=x.value);state.answers.sheet=a;if(fields.some(x=>!a[x[0]]?.trim())){alert("すべての項目を記入してください。");return}state.completed.sheet=true;save();alert("LLM挙動分析シートを保存しました。")}}
  function quizView(){const q=state.quiz.index||0;if(state.quiz.result!==undefined){const pass=state.quiz.result>=8;view.innerHTML=`<p class="m1-kicker">FINAL QUIZ</p><h1 class="m1-title">総合テスト結果</h1><section class="m1-result ${pass?"":"fail"}"><h2>${state.quiz.result} / 10 問正解</h2><p>${pass?"合格です。AI出力は候補として扱い、人間が検証・判断してください。":"80%（8問）以上で合格です。基礎知識と実習を見直して再挑戦してください。"}</p></section><div class="m1-actions"><button class="m1-secondary" id="retry">もう一度挑戦</button><button class="m1-primary" data-go="results">学習結果へ</button></div>`;view.querySelector("#retry").onclick=()=>{state.quiz={};save();quizView()};view.querySelector("[data-go]").onclick=()=>render("results");return}const item=quiz[q];view.innerHTML=`<p class="m1-kicker">FINAL QUIZ ${q+1} / 10</p><h1 class="m1-title">総合テスト</h1><section class="m1-quiz-card"><h3>${item[0]}</h3>${item[1].map((x,i)=>`<label class="m1-option"><input type="radio" name="q" value="${i}">${x}</label>`).join("")}<div class="m1-actions"><button class="m1-primary" id="next">${q===9?"結果を見る":"次へ"}</button></div></section>`;document.getElementById("next").onclick=()=>{const c=view.querySelector('input[name="q"]:checked');if(!c){alert("回答を選択してください。");return;}state.quiz.answers ||= [];state.quiz.answers[q]=Number(c.value);if(q<9)state.quiz.index=q+1;else{state.quiz.result=state.quiz.answers.reduce((n,x,i)=>n+(x===quiz[i][2]?1:0),0);if(state.quiz.result>=8)state.completed.quiz=true}save();quizView()}}
  function results(){const done=Object.keys(state.completed).filter(x=>x.startsWith("exercise-")).length;view.innerHTML=`<p class="m1-kicker">RESULTS</p><h1 class="m1-title">学習結果</h1><div class="m1-grid"><section class="m1-card"><p class="m1-kicker">COMPLETED</p><div class="l2-score">${done} / 8</div><p>完了した実習</p></section><section class="m1-card"><p class="m1-kicker">QUIZ</p><div class="l2-score">${state.quiz.result ?? "-"} / 10</div><p>総合テスト</p></section><section class="m1-card"><p class="m1-kicker">SHEET</p><div class="l2-score">${state.completed.sheet?"完了":"未完了"}</div><p>LLM挙動分析シート</p></section></div><section class="m1-card" style="margin-top:16px"><h2>次に確認すること</h2><ul><li>トークン、確率生成、ハルシネーションを自分の言葉で説明できるか</li><li>AI回答の事実・推測・不足情報を分けられるか</li><li>業務でAIを使う前に、情報管理と人間確認を実施できるか</li></ul></section>`}
  function glossary(){const words=[["LLM","大量の文章データからパターンを学び、次のトークンを予測して文章を生成するモデル。"],["トークン","LLMが文章を処理する小さな単位。必ずしも一つの単語と一致しない。"],["確率生成","複数の候補から、続きやすい候補を選びながら文章を作る仕組み。"],["コンテキスト","入力文、会話履歴、指定条件など、回答に影響する情報。"],["ハルシネーション","存在しない・誤った・確認できない情報を自然な文章で生成する現象。"],["一次情報","公式ドキュメント、公式発表、実際の環境など、確認の根拠となる情報。"]];view.innerHTML=`<p class="m1-kicker">GLOSSARY</p><h1 class="m1-title">用語集</h1><section class="m1-card"><dl class="l2-glossary">${words.map(x=>`<dt>${x[0]}</dt><dd>${x[1]}</dd>`).join("")}</dl></section>`}
  function render(page){navRender(page);if(page==="home")home();if(page==="theory")theory();if(page==="exercises")exercisesList();if(page==="sheet")sheet();if(page==="quiz")quizView();if(page==="results")results();if(page==="glossary")glossary();lucide.createIcons()};render("home");
})();
