const profileKey = "ai-course-profile";
const courseKey = "ai-course-state";
const profile = JSON.parse(localStorage.getItem(profileKey) || "{}");
const course = JSON.parse(localStorage.getItem(courseKey) || "{}");
const name = profile.name || "受講生A";
const role = profile.role || "受講者";
const completed = course.completedModules || [];
const submitted = (course.submissions || (course.submitted ? [5] : [])).length;
const byId = (id) => document.getElementById(id);
document.querySelectorAll(".profile-name").forEach((element) => element.textContent = name);
byId("profile-role").textContent = role;
byId("avatar-initials").textContent = name.slice(0, 1);
byId("name-input").value = name;
byId("role-input").value = role;
byId("reminder-toggle").checked = Boolean(profile.reminder);
byId("save-status-toggle").checked = profile.showSaveStatus !== false;
byId("profile-progress").textContent = `${Math.round(completed.length / 10 * 100)}%`;
byId("profile-modules").textContent = `${completed.length} / 10`;
byId("profile-submissions").textContent = `${submitted} 件`;
byId("save-profile").addEventListener("click", () => {
  const updatedName = byId("name-input").value.trim() || "受講生A";
  const updatedProfile = { name: updatedName, role: byId("role-input").value.trim() || "受講者", reminder: byId("reminder-toggle").checked, showSaveStatus: byId("save-status-toggle").checked };
  localStorage.setItem(profileKey, JSON.stringify(updatedProfile));
  document.querySelectorAll(".profile-name").forEach((element) => element.textContent = updatedName);
  byId("profile-role").textContent = updatedProfile.role;
  byId("avatar-initials").textContent = updatedName.slice(0, 1);
  byId("profile-save-message").textContent = "プロフィールを保存しました。";
});
lucide.createIcons();
