const requestedModule = Number(new URLSearchParams(window.location.search).get("module")) || 5;
const currentModule = COURSE_MODULES.find((module) => module.id === requestedModule) || COURSE_MODULES[4];
const modulePlan = COURSE_PLAN[currentModule.id];
const key = `ai-course-task-${currentModule.id}`;
const progressKey = "ai-course-state";
const state = JSON.parse(localStorage.getItem(key) || "{}");
const progressState = JSON.parse(localStorage.getItem(progressKey) || "{}");
const profile = JSON.parse(localStorage.getItem("ai-course-profile") || "{}");
document.querySelectorAll(".profile-name").forEach((element) => element.textContent = profile.name || "受講生A");
state.answers ||= {}; state.checks ||= {}; state.completedModules ||= [];
let currentStep = 1;
const fields = ["prompt","correct","uncertain","evidence"];
const get = (id) => document.getElementById(id);
const firstStep = document.querySelector('[data-step="1"]');
const secondStep = document.querySelector('[data-step="2"]');
document.title = `${currentModule.title} | AI業務活用研修`;
document.querySelector(".task-intro .tag").textContent = `MODULE ${String(currentModule.id).padStart(2, "0")}`;
document.querySelector(".task-intro h1").textContent = currentModule.title;
document.querySelector(".task-intro p").textContent = currentModule.summary;
firstStep.querySelector(".callout.info p").textContent = currentModule.objective;
firstStep.querySelector(".body-text").textContent = currentModule.scenario;
firstStep.querySelector(".log-head h3").textContent = currentModule.evidenceTitle;
firstStep.querySelector(".log-box").textContent = currentModule.evidence;
get("show-all-logs").textContent = currentModule.evidenceTitle.includes("ログ") ? "全ログを表示" : "資料を確認";
firstStep.querySelector(".deliverables").innerHTML = currentModule.deliverables.map((item) => `<li>${item}</li>`).join("");
firstStep.querySelector(".callout.hint p").textContent = currentModule.hint;
const modulePlanBlock = document.createElement("section");
modulePlanBlock.className = "module-plan";
modulePlanBlock.innerHTML = `<div><p class="kicker">MODULE PLAN</p><h3>${modulePlan.duration}</h3><span>成果物：${modulePlan.outcome}</span></div><ol>${modulePlan.days.map((day, index) => `<li><b>DAY ${index + 1}</b><span>${day}</span></li>`).join("")}</ol>`;
firstStep.querySelector(".callout.info").after(modulePlanBlock);
secondStep.querySelector(".field-help").textContent = "資料の状況を説明し、原因や対応方針について質問してみましょう。";
get("prompt").placeholder = currentModule.promptHint;
get("ai-response").querySelector("p").innerHTML = `<strong>AIの回答例：</strong><br>${currentModule.aiPreview}`;
get("evidence").closest("textarea").previousElementSibling.previousElementSibling.textContent = "3 根拠となる情報";
get("summary-evidence").previousElementSibling.textContent = "根拠となる情報";
document.querySelector('[data-check="logs"]').parentElement.querySelector("span").textContent = "資料を確認し、重要な点を整理した";
fields.forEach((id) => { get(id).value = state.answers[id] || ""; get(id).addEventListener("input", saveState); });
document.querySelectorAll("[data-check]").forEach((box) => { box.checked = !!state.checks[box.dataset.check]; box.addEventListener("change", saveState); });
function saveState(){ fields.forEach((id) => state.answers[id] = get(id).value); document.querySelectorAll("[data-check]").forEach((box) => state.checks[box.dataset.check] = box.checked); localStorage.setItem(key, JSON.stringify(state)); get("prompt-count").textContent = get("prompt").value.length; get("save-status").innerHTML = '<i data-lucide="cloud-check"></i> 保存済み'; lucide.createIcons(); }
function selectStep(number){ currentStep = Math.max(1, Math.min(4, number)); document.querySelectorAll(".step-card").forEach((card) => card.classList.toggle("active", Number(card.dataset.step) === currentStep)); document.querySelectorAll("#mobile-step-tabs button").forEach((button) => button.classList.toggle("active", Number(button.dataset.step) === currentStep)); get("slide-counter").textContent = `ステップ ${currentStep} / 4`; get("previous-slide").disabled = currentStep === 1; get("next-slide-top").disabled = currentStep === 4; if(currentStep === 4) renderSummary(); window.scrollTo({top:0,behavior:"smooth"}); }
function renderSummary(){ ["correct","uncertain","evidence"].forEach((id) => get(`summary-${id}`).textContent = state.answers[id]?.trim() || "未入力"); const names = {logs:"ログを確認し、原因候補を整理した",verify:"AIの回答を鵜呑みにせず検証した",evidence:"自分の根拠をログから示した"}; get("review-checks").innerHTML = Object.entries(names).map(([id,label]) => `<p><i data-lucide="${state.checks[id] ? "check-circle-2" : "circle"}"></i>${label}</p>`).join(""); lucide.createIcons(); }
get("mobile-step-tabs").innerHTML = ["内容確認","AIに質問","自分で検証","提出"].map((label,index) => `<button data-step="${index+1}">${index+1}. ${label}</button>`).join("");
document.querySelectorAll(".step-next").forEach((button) => button.addEventListener("click", () => { saveState(); selectStep(Number(button.dataset.next)); }));
document.querySelectorAll("#mobile-step-tabs button").forEach((button) => button.addEventListener("click", () => selectStep(Number(button.dataset.step))));
get("previous-slide").addEventListener("click", () => selectStep(currentStep - 1));
get("next-slide-top").addEventListener("click", () => { saveState(); selectStep(currentStep + 1); });
get("prompt").addEventListener("input", () => get("prompt-count").textContent = get("prompt").value.length);
get("prompt-count").textContent = get("prompt").value.length;
document.querySelectorAll(".chip").forEach((chip) => chip.addEventListener("click", () => { get("prompt").value = `${get("prompt").value}${get("prompt").value ? "\n" : ""}${chip.dataset.prompt}`; saveState(); }));
get("ask-ai").addEventListener("click", () => { if(!get("prompt").value.trim()){ get("prompt").focus(); return; } saveState(); get("ai-response").classList.remove("hidden"); });
get("save-draft").addEventListener("click", () => { saveState(); get("save-status").innerHTML = '<i data-lucide="cloud-check"></i> 下書きを保存しました'; lucide.createIcons(); });
get("submit-task").addEventListener("click", () => { saveState(); if(!state.answers.correct?.trim() || !state.answers.uncertain?.trim() || !state.answers.evidence?.trim() || !Object.values(state.checks).every(Boolean)){ alert("提出前に、3つの検証項目とチェックリストをすべて完了してください。"); return; } state.submitted = true; progressState.completedModules ||= []; progressState.submissions ||= []; if(!progressState.completedModules.includes(currentModule.id - 1)) progressState.completedModules.push(currentModule.id - 1); if(!progressState.submissions.includes(currentModule.id)) progressState.submissions.push(currentModule.id); progressState.submitted = true; localStorage.setItem(key, JSON.stringify(state)); localStorage.setItem(progressKey, JSON.stringify(progressState)); get("result-dialog").showModal(); });
get("show-all-logs").addEventListener("click", () => alert("この演習では、表示されている資料を根拠として使用します。"));
selectStep(1); lucide.createIcons();
